name: nordic_nrf_discovery
description: This package contains logic to discover Nordic NRF devices. This is only really relevant if you don't have your own discovery logic already.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.2.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
